docs/en/resources/tools/_index.md
Fix broken links to auth source page.
Fixes #282
=> docs(tools): fix broken links

docs/en/resources/sources/dgraph.md
=> docs: update description for draph

cmd/root.go, internal/util/util.go
Add functionality to add and retrieve logger from Go context.
=> chore: add and retrieve logger from context

.github/release-please.yml, README.md, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/how-to/deploy_gke.md
Include release please annotations to update version bumps in docs automatically, refer [here](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) for release please documentations.
=> docs: release please update versions on docs automatically

.github/release-please.yml, README.md, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/how-to/deploy_gke.md
Reverts googleapis/genai-toolbox#319
=> Revert "docs: release please update versions on docs automatically"

docs/en/getting-started/local_quickstart.md
This PR fixes indentation issues in local_quickstart.md (lines 311-371) to ensure proper Markdown rendering.
=> chore: fix indentation issue in Quickstart

.github/workflows/cloud_build_failure_reporter.yml, .github/workflows/schedule_reporter.yml
Along with creating the required files, this PR adds changes similar to https://github.com/googleapis/genai-toolbox-llamaindex-python/pull/32
=> chore: add cloud build reporter for integration tests 

.github/blunderbuss.yml
documentation: https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss#usage
=> ci: Add blunderbuss config

internal/server/common_test.go, internal/server/mcp.go, internal/server/mcp/types.go, internal/server/mcp_test.go, internal/server/server.go
Tested sse implementation with MCP [inspector](https://modelcontextprotocol.io/docs/tools/inspector) tool.
=> feat: support sse

internal/server/mcp/method.go, internal/server/mcp/types.go, tests/alloydb_pg_integration_test.go, tests/cloud_sql_mssql_integration_test.go, tests/cloud_sql_mysql_integration_test.go, tests/cloud_sql_pg_integration_test.go, tests/common_test.go, tests/mssql_integration_test.go, tests/mysql_integration_test.go, tests/postgres_integration_test.go, tests/tool_test.go
forgot to add the `IsError` field previously.
Also added integration tests for that.
=> chore: update tool call response

docs/en/concepts/telemetry/index.md, internal/server/instrumentation.go, internal/server/mcp.go, internal/server/mcp/types.go
Add traces, metrics, and logs to mcp router.
=> feat: add telemetry for mcp

.ci/continuous.release.cloudbuild.yaml, .ci/integration.cloudbuild.yaml
Revert "ci: Increase Cloud Build vCPU"
=> Revert "ci: Increase Cloud Build vCPU"

.github/ISSUE_TEMPLATES/bug_report.yml, .github/ISSUE_TEMPLATES/config.yml, .github/ISSUE_TEMPLATES/feature_request.yml, .github/ISSUE_TEMPLATES/question.yml
Add new issue forms for filing a bug on Toolbox.
=> chore: add issue forms

docs/en/resources/sources/alloydb-pg.md, go.mod, internal/sources/alloydbpg/alloydb_pg.go, internal/sources/util.go, tests/alloydb_pg_integration_test.go, tests/cloud_sql_mssql_integration_test.go, tests/cloud_sql_mysql_integration_test.go, tests/cloud_sql_pg_integration_test.go, tests/source_test.go
Add IAM support for AlloyDB source connection: https://pkg.go.dev/cloud.google.com/go/alloydbconn#section-readme
=> feat: Add IAM authentication to AlloyDB Source

.ci/integration.cloudbuild.yaml, go.mod, tests/common_test.go, tests/spanner_integration_test.go, tests/tool_test.go
=> ci: Add Spanner integration tests

.github/workflows/tests.yaml, internal/server/api_test.go, internal/server/common_test.go
Add unit test for Tool invoke handler.
Exclude config.go from coverage calculation.
=> ci: Increase unit test coverage

internal/sources/bigquery/bigquery.go, internal/sources/bigtable/bigtable.go
Add user agent for metrics tracing.
=> chore: Add user agent to Bigtable and BigQuery

.github/workflows/tests.yaml
unit test coverage 44.6% --> 53.6
=> ci: Correct excluded file in unit test coverage

README.md, docs/en/getting-started/introduction/_index.md
Minor edit to description of Toolbox to avoid some sensitivity around production/enterprise suitability as that may imply compliance features or guarantees which aren't suitable to an early stage product.
=> docs: update MCP Toolbox description

DEVELOPER.md
We have refactored our tests. Fix instruction in DEVELOPER.md to match the latest setting.
=> docs: Update testing instruction in DEVELPER.md

docs/en/resources/tools/bigtable-sql.md
=> chore: fix bigtable doc typo

docs/en/resources/tools/bigquery-sql.md, docs/en/samples/bigquery/colab_quickstart_bigquery.ipynb
For issue https://github.com/googleapis/genai-toolbox/issues/566
=> docs: add note for bigquery parameter replacement introduction.

README.md, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/how-to/deploy_docker.md, docs/en/how-to/deploy_toolbox.md, docs/en/samples/bigquery/local_quickstart.md
Fixes [#208](https://github.com/googleapis/mcp-toolbox-sdk-python/issues/208)
=> docs: Update docs to guide with proper lifecycle management

docs/en/resources/tools/bigquery-execute-sql.md, docs/en/resources/tools/bigquery-get-dataset-info.md, docs/en/resources/tools/bigquery-get-table-info.md, docs/en/resources/tools/bigquery-list-dataset-ids.md, docs/en/resources/tools/bigquery-list-table-ids.md, internal/server/config.go, internal/tools/bigqueryexecutesql/bigqueryexecutesql.go, internal/tools/bigqueryexecutesql/bigqueryexecutesql_test.go, internal/tools/bigquerygetdatasetinfo/bigquerygetdatasetinfo.go, internal/tools/bigquerygetdatasetinfo/bigquerygetdatasetinfo_test.go, internal/tools/bigquerygettableinfo/bigquerygettableinfo.go, internal/tools/bigquerygettableinfo/bigquerygettableinfo_test.go, internal/tools/bigquerylistdatasetids/bigquerylistdatasetids.go, internal/tools/bigquerylistdatasetids/bigquerylistdatasetids_test.go, internal/tools/bigquerylisttableids/bigquerylisttableids.go, internal/tools/bigquerylisttableids/bigquerylisttableids_test.go, tests/bigquery/bigquery_integration_test.go
Added five new tools and corresponding documents:
1. bigquery-execute-sql
2. bigquery-list-dataset-ids
3. bigquery-list-table-ids
4. bigquery-get-dataset-info
5.  bigquery-get-table-info
=> feat: add new bigquery tools.

tests/alloydbpg/alloydb_pg_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/common.go, tests/postgres/postgres_integration_test.go
Add the template parameters integration test to `postgres` source and `cloudsql-postgres` source.
=> test: add templateParam postgres-sql tests to other pg source

internal/tools/mssqlsql/mssqlsql.go, internal/tools/mssqlsql/mssqlsql_test.go, tests/cloudsqlmssql/cloud_sql_mssql_integration_test.go, tests/common.go, tests/mssql/mssql_integration_test.go
Add `templateParameters to support non-filter parameters and DDL statements.
Part of https://github.com/googleapis/genai-toolbox/issues/535
=> feat: add templateParameters field for mssqlsql

docs/en/resources/tools/alloydb-ai-nl.md
=> docs(tools/alloydbainl): update broken links

cmd/root.go, cmd/root_test.go, go.mod, go.sum
Use fsnotify to detect edits to the tools config file (will only trigger on save of file).
=> feat: detect edits in tools file

docs/en/resources/sources/http.md, internal/sources/http/http.go, internal/sources/http/http_test.go
Fix issue: https://github.com/googleapis/genai-toolbox/issues/661
=> feat: Support disable SSL verification for HTTP Source

.ci/continuous.release.cloudbuild.yaml, .ci/versioned.release.cloudbuild.yaml, Dockerfile
Built Toolbox as a multi-platform container.
Fix #686
=> chore: support linux/arm64 platform for Docker

internal/server/mcp.go, internal/server/mcp_test.go
Error with "not supporting batch requests" message when client send batch request.
=> chore: error response when client sent batch requests

internal/server/api.go, internal/server/common_test.go, internal/server/mcp.go, internal/server/mcp_test.go, internal/server/server.go
Introduce the `resourceManager` struct to handle how the server stores resources (sources, authServices, tools, toolsets)
=> refactor: introduce resourceManager to handle server resources

tests/alloydbpg/alloydb_pg_integration_test.go, tests/bigquery/bigquery_integration_test.go, tests/bigtable/bigtable_integration_test.go, tests/cloudsqlmssql/cloud_sql_mssql_integration_test.go, tests/cloudsqlmysql/cloud_sql_mysql_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/common.go, tests/couchbase/couchbase_integration_test.go, tests/http/http_integration_test.go, tests/mssql/mssql_integration_test.go, tests/mysql/mysql_integration_test.go, tests/postgres/postgres_integration_test.go, tests/redis/redis_test.go, tests/spanner/spanner_integration_test.go, tests/sqlite/sqlite_integration_test.go, tests/tool.go, tests/valkey/valkey_test.go
Add integration tests to check for `null` columns. ref #757
=> test: add null column test case

tests/alloydbpg/alloydb_pg_integration_test.go, tests/bigquery/bigquery_integration_test.go, tests/bigtable/bigtable_integration_test.go, tests/cloudsqlmssql/cloud_sql_mssql_integration_test.go, tests/cloudsqlmysql/cloud_sql_mysql_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/common.go, tests/couchbase/couchbase_integration_test.go, tests/http/http_integration_test.go, tests/mssql/mssql_integration_test.go, tests/mysql/mysql_integration_test.go, tests/postgres/postgres_integration_test.go, tests/redis/redis_test.go, tests/spanner/spanner_integration_test.go, tests/sqlite/sqlite_integration_test.go, tests/tool.go, tests/valkey/valkey_test.go
Note: null optional parameters currently doesn't work with BigQuery.
=> test: integration tests for null optional parameters

internal/sources/bigquery/bigquery.go, internal/tools/bigquery/bigqueryexecutesql/bigqueryexecutesql.go
Updated dry run in execute sql to also include a location, fix the potential issue in PR #925.
=> chore: fix dry run location

.github/release-please.yml, docs/en/getting-started/configure.md, docs/en/getting-started/local_quickstart_go.md, docs/en/getting-started/mcp_quickstart/_index.md
docs: Add Toolbox Go SDK Quickstart
=> docs: add Toolbox Go SDK quickstart

internal/server/static/css/style.css, internal/server/static/js/navbar.js
Clicking on the MCP Toolbox Logo will redirect to the Toolbox UI Homepage.
=> chore(ui): logo redirects to homepage for Toolbox UI

internal/tools/bigquery/bigquerysql/bigquerysql.go, internal/tools/bigtable/bigtable.go, internal/tools/couchbase/couchbase.go, internal/tools/mssql/mssqlsql/mssqlsql.go, internal/tools/mysql/mysqlsql/mysqlsql.go, internal/tools/parameters.go, internal/tools/postgres/postgressql/postgressql.go, internal/tools/spanner/spannersql/spannersql.go, internal/tools/sqlitesql/sqlitesql.go, internal/tools/tidb/tidbsql/tidbsql.go
Added check to `ProcessParameters()` to check for parameter name duplication and simplify the function.
ref: #1135
=> chore: refactor process parameters function

cmd/root.go, internal/prebuiltconfigs/prebuiltconfigs.go, internal/prebuiltconfigs/prebuiltconfigs_test.go
---
This PR changes the help description in the prebuilt flag from hardcoded source options to dynamically fetching it from the prebuilt configs.
---
[bug/issue](https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/new/choose)
=> chore(prebuilt): dynamically generate --prebuilt flag options

.github/blunderbuss.yml, .github/labels.yaml
Adds Looker and @drstrangelooker for issue assignment.
=> chore(ci/cd): add looker label and assignee 

cmd/root.go, docs/en/getting-started/configure.md, internal/tools/looker/lookergetdashboards/lookergetdashboards.go
looker-getdash-board uses the Authorized helper function.
---
- [x ] Make sure you reviewed
[bug/issue](https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/new/choose)
- [ x] Ensure the tests and linter pass
- [ x] Code coverage does not decrease (if any source code was changed)
- [ x] Appropriate docs were updated (if necessary)
- [x ] Make sure to add `!` if this involve a breaking change
=> fix(tools/looker): lookergetdashboards uses proper Authorized helper func

internal/server/api_test.go, internal/server/common_test.go, internal/server/mcp.go, internal/server/mcp/jsonrpc/jsonrpc_test.go, internal/server/mcp_test.go
Our coverage is falling below minimum (40%). Add unit tests for unauthorized calls.
=> test: add unit tests for unauthorized calls

docs/en/resources/tools/looker/looker-get-explores.md, internal/tools/looker/lookergetexplores/lookergetexplores.go, tests/looker/looker_integration_test.go
…tool
---
Add description to output of get_models, as well as add output details to docs
---
[bug/issue](https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/new/choose)
🛠️ Fixes #1246
=> feat(tools/looker): Add description for looker-get-models tool

.github/labels.yaml
---
> Should include a concise description of the changes (bug or feature), it's
> impact, along with a summary of the solution
---
=> chore: Add label for release candidate

.ci/integration.cloudbuild.yaml, .ci/test_with_coverage.sh
---
> Should include a concise description of the changes (bug or feature), it's
> impact, along with a summary of the solution
---
=> ci: ignore MySQL tests

.ci/versioned.release.cloudbuild.yaml
---
> Should include a concise description of the changes (bug or feature), it's
> impact, along with a summary of the solution
---
=> chore: update binary metadata

internal/tools/mongodb/mongodbfind/mongodbfind.go, tests/mongodb/mongodb_integration_test.go
The projection checking block in `getOptions` exists early previously, resulting in the limit not being set.
🛠️ Fixes https://github.com/googleapis/genai-toolbox/issues/1491
=> fix(tool/mongodb-find): fix find tool `limit` field

docs/en/resources/tools/looker/looker-add-dashboard-element.md, docs/en/resources/tools/looker/looker-get-dashboards.md
Fix descriptions in Looker tools docs
=> docs(sources/looker): Fix typos in Looker tools (#1608)

internal/sources/cloudsqlmysql/cloud_sql_mysql.go, internal/sources/mysql/mysql.go
---
Audit your applications by using the following sql to track program name
```
SELECT
session_connect_attrs.ATTR_VALUE AS program_name,
processlist.*
FROM
information_schema.processlist
LEFT JOIN
performance_schema.session_connect_attrs
ON
(processlist.ID = session_connect_attrs.PROCESSLIST_ID AND session_connect_attrs.ATTR_NAME = "program_name");
```
---
🛠️ Fixes …
=> feat: add program name to MySQL connections

docs/en/getting-started/quickstart/go/genkit/quickstart.go, docs/en/getting-started/quickstart/go/langchain/quickstart.go
---
Updating the Gemini model from 1.5-flash to 2.0-flash in the Go Quickstart tests for LangChain and Genkit samples.
This PR fixes the failing tests in https://github.com/googleapis/genai-toolbox/pull/1572
---
=> chore: Update model in Go Quickstart tests

DEVELOPER.md, tests/looker/looker_integration_test.go
---
The timeout on the server was one minute, but the tests were sometimes running longer. Made timeout 5 minutes.
> Should include a concise description of the changes (bug or feature), it's
> impact, along with a summary of the solution
---
🛠️ Fixes #1635
=> test(looker): Expand timeout on tests
