README.md, docs/en/getting-started/configure.md, docs/en/resources/authSources/_index.md
Add the bash command to `pip install` the package directly in the README for a quicker start.
Also add “SDK” after “Toolbox LangChain” to clearly show that “Toolbox LangChain” is an SDK.
> [!NOTE]
> We had released the PyPI package for Toolbox LangChain SDK as `toolbox-langchain` and not `toolbox-langchain-sdk` but it still makes sense to call it “Toolbox LangChain SDK” in natural language.
=> doc: Update README to improve Toolbox LangChain SDK installation instructions

docs/en/getting-started/local_quickstart.md
Updates the local_quickstart to clarify pip as a requirement and connect using psql consistently.
=> docs: clarify pip as a requirement

internal/tools/parameters.go, internal/tools/parameters_test.go
`items` are not specified in the manifest for parameters, which means the client doesn't parse them correctly when presented to the LLMs. This PR adds `items` as part of manifest.
Example manifest:
```
{
"serverVersion": "0.1.0",
"tools": {
"tool_name": {
"description": "description of the tool...",
"parameters": [{
"name": "foos",
"type": "array",
"description": "A list of foo.",
"authSources": [],
"items": {"name": "foo", "type": "string", "description": "foobar.", "authSources": []}
}]
}
}
}
```
Fixes #292 🦕
=> fix: add items to parameter manifest

internal/tools/parameters_test.go, internal/util/util.go
Fixes #291 by throwing a descriptive error when items is not provided.
Example of error when `items` field not provided for array parameter:
```
2025-02-18T14:07:58.77173-08:00 ERROR "unable to parse tool file at \"tools.yaml\": unable to parse as \"postgres-sql\": unable to parse as \"array\": unable to parse 'items' field: error parsing parameters: nothing to unmarshal"
```
=> fix: throw error when items field is missing from array parameter

internal/tools/parameters.go, internal/tools/parameters_test.go, internal/util/util.go
Check common parameters for required fields. Throw an error if name or description is not provided.
Example of error when `description` field not provided:
```
2025-02-18T14:11:55.475101-08:00 ERROR "unable to parse tool file at \"tools.yaml\": unable to parse as \"postgres-sql\": unable to parse as \"array\": Key: 'CommonParameter.Desc' Error:Field validation for 'Desc' failed on the 'required' tag"
```
=> fix: validate required common fields for parameters

cmd/root.go, cmd/root_test.go, docs/en/resources/authServices/_index.md, docs/en/resources/authServices/google.md, docs/en/resources/tools/_index.md, internal/auth/auth.go, internal/auth/google/google.go, internal/server/api.go, internal/server/api_test.go, internal/server/config.go, internal/server/server.go, internal/testutils/testutils.go, internal/tools/dgraph/dgraph.go, internal/tools/dgraph/dgraph_test.go, internal/tools/mssqlsql/mssqlsql.go, internal/tools/mssqlsql/mssqlsql_test.go, internal/tools/mysqlsql/mysqlsql.go, internal/tools/mysqlsql/mysqlsql_test.go, internal/tools/neo4j/neo4j.go, internal/tools/neo4j/neo4j_test.go, internal/tools/parameters.go, internal/tools/parameters_test.go, internal/tools/postgressql/postgressql.go, internal/tools/postgressql/postgressql_test.go, internal/tools/spanner/spanner.go, internal/tools/spanner/spanner_test.go, internal/tools/tools.go, tests/common_test.go
Rename existing `authSource` to `authService` through deprecation. `AuthService` more clearly distinguishes it from `Sources` objects. 
`authSources` will be converted into `authServices` after the unmarshalling process. A warning log is shown if `authSources` are used (for both within tools parameters and defining auth services):
```
2025-02-20T13:57:51.156025-08:00 WARN "`authSources` is deprecated, use `authServices` for parameters instead"
2025-02-20T13:57:51.156569-08:00 WARN "`authSources` is deprecated, use `authServices` instead"
2025-02-20T13:57:52.047584-08:00 INFO "Initialized 1 sources."
...
```
The manifest generated will continue to use `authSources` to keep compatibility with the sdks:
```
{
"serverVersion":"0.1.0",
"tools":{
"test_tool2":{
"description":"Use this tool to …
```
=> feat!: deprecate authsource in favor of authservice

docs/en/resources/tools/spanner-sql.md
Update `spanner-sql` kind in example. It was previously updated throughout the doc, except for the example.
It should be `spanner-sql` instead of `spanner`.
Fixes #302
=> docs(tool/spanner-sql): fix spanner-sql kind in example

internal/server/server.go
The above message is more accurate than the current `"Hello world!"` message. [wiki](https://en.wikipedia.org/wiki/%22Hello,_World!%22_program)
=> chore: update "Hello, World!" message from the default route of Toolbox.

DEVELOPER.md
Was getting a 404 on link referencing SDK developer guide.
I think it is meant to point at https://github.com/googleapis/genai-toolbox-langchain-python/blob/main/DEVELOPER.md
=> chore: update sdk reference in DEVELOPER.md

.github/release-please.yml, README.md, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/how-to/deploy_gke.md
Include release please annotations to update version bumps in docs automatically, refer [here](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) for release please documentations.
=> docs: release please update versions on docs automatically

README.md
This slightly improves readability as "full documentation" is highlighted with the link, which is more accurate.
=> doc: Improve full doc link in README

internal/tools/mssqlsql/mssqlsql.go, internal/tools/mysqlsql/mysqlsql.go, internal/tools/postgressql/postgressql.go, internal/tools/spanner/spanner.go
This PR is to remove the `NewGenericTool` function within tools. 
This function was previously added when we are trying to consolidate the three postgres tools. However, since we merged it into a single `postgressql` tool, these functions are not used anymore.
=> chore: cleanup unused function

docs/en/getting-started/local_quickstart.md
This PR fixes an incorrect or outdated LlamaIndex documentation URL in `local_quickstart.md`.
=> docs: update LlamaIndex quickstart URL

docs/en/how-to/deploy_gke.md
Pull the docker image with `latest` tag instead of the specific version number.
=> docs: update docs to pull docker image with latest tag

internal/server/api_test.go, internal/server/common_test.go
move common tests functions in server into a separate file.
=> refactor(server): move common tests functions into a separate file

internal/server/api.go, internal/server/api_test.go, internal/server/common_test.go, internal/server/mcp.go, internal/server/mcp/types.go, internal/server/mcp_test.go, internal/server/server.go
Add http post endpoint for mcp at `api/mcp`. Types are based on the 2024-11-05 [specification](https://github.com/modelcontextprotocol/specification/blob/main/schema/2024-11-05/schema.ts).
Tested with:
`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "foo"}' http://127.0.0.1:5000/mcp`
Response:
`{"jsonrpc":"2.0","id":1,"result":{}}`
Test cases included.
=> feat: add http post endpoint for mcp

internal/server/mcp.go, internal/server/mcp/method.go, internal/server/mcp/types.go, internal/server/mcp_test.go
Add support for the `initialize` phase for mcp's connection lifecycle.
After receiving the `initialize` request, the server will respond with it's own capabilities and information. Since there are only one protocol supported, we don't have to do protocol version comparison. Toolbox server will response with the default protocol version.
Initial support for MCP Tools will not include list changed notification.
Test cases included.
=> feat: support connection lifecycle initialize phase

.github/renovate.json5
Currently renovate bot doesn't run go mod tidy, hence, all the renovate bot PR failed the lint checks.
=> fix: renovatebot to run go mod tidy post update

internal/server/common_test.go, internal/tools/dgraph/dgraph.go, internal/tools/mssqlsql/mssqlsql.go, internal/tools/mysqlsql/mysqlsql.go, internal/tools/neo4j/neo4j.go, internal/tools/parameters.go, internal/tools/parameters_test.go, internal/tools/postgressql/postgressql.go, internal/tools/spanner/spanner.go, internal/tools/tools.go
Parse existing toolbox manifest to ToolsList that is compatible with MCP [tools definition](https://modelcontextprotocol.io/docs/concepts/tools#tool-definition-structure).
AuthServices will be omitted since MCP doesn't support auth at this time.
=> feat: parse manifest to tools list

internal/server/api_test.go, internal/server/common_test.go, internal/server/mcp.go, internal/server/mcp/method.go, internal/server/mcp/types.go, internal/server/mcp_test.go, internal/tools/dgraph/dgraph.go, internal/tools/mssqlsql/mssqlsql.go, internal/tools/mysqlsql/mysqlsql.go, internal/tools/neo4j/neo4j.go, internal/tools/parameters.go, internal/tools/parameters_test.go, internal/tools/postgressql/postgressql.go, internal/tools/spanner/spanner.go, internal/tools/tools.go, internal/tools/toolsets.go
Add `tools/list` method. 
Example to call the `tools/list` method:
`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "tools/list"}' http://127.0.0.1:5000/mcp`
Toolbox will response. with a valid JSONRPCResponse with a list of all tools available.
=> feat: add tools list method

internal/server/mcp.go, internal/server/mcp/method.go, internal/server/mcp/types.go, tests/alloydb_pg_integration_test.go, tests/cloud_sql_mssql_integration_test.go, tests/cloud_sql_mysql_integration_test.go, tests/cloud_sql_pg_integration_test.go, tests/mssql_integration_test.go, tests/mysql_integration_test.go, tests/postgres_integration_test.go, tests/tool_test.go
Add `tools/call` method. 
Example to call the `tools/list` method:
`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params":{"name": "my-tool"}}' http://127.0.0.1:5000/mcp`
Toolbox will response with a valid JSONRPCResponse of the result of tool invocation.
=> feat: add tool call method

internal/server/mcp.go
variable `id` is used in metrics to record the session id.
`json.Number` will throw an error when casting to string with `.(string)`.
=> fix: fix casting to string

docs/en/resources/sources/alloydb-pg.md, docs/en/resources/sources/cloud-sql-mssql.md, docs/en/resources/sources/cloud-sql-mysql.md, docs/en/resources/sources/cloud-sql-pg.md, docs/en/resources/sources/postgres.md, docs/en/resources/tools/dgraph-dql.md, docs/en/resources/tools/mssql-sql.md, docs/en/resources/tools/mysql-sql.md, docs/en/resources/tools/neo4j-cypher.md, docs/en/resources/tools/postgres-sql.md, docs/en/resources/tools/spanner-sql.md, internal/server/config.go
fix some typos and formats in code & docs
`neo4jrc` should be `neo4jsrc`
=> docs: fix misc typos

.ci/continuous.release.cloudbuild.yaml
Integration test encountered `signal: killed` error and could be due to out-of-memory issue. Try increasing the Cloud Build vCPU: https://cloud.google.com/build/docs/optimize-builds/increase-vcpu-for-builds
=> ci: Increase Cloud Build vCPU

docs/en/resources/tools/http.md
Fixed a typo in the doc for HTTP tool
=> docs: fix typo in http tool

docs/en/resources/sources/cloud-sql-pg.md, internal/sources/cloudsqlmssql/cloud_sql_mssql.go, internal/sources/cloudsqlmysql/cloud_sql_mysql.go, internal/sources/cloudsqlpg/cloud_sql_pg.go, internal/sources/util.go, tests/alloydb_pg_integration_test.go, tests/cloud_sql_pg_integration_test.go
Add IAM support for Cloud SQL source connection using Go language connector: https://pkg.go.dev/cloud.google.com/go/cloudsqlconn#section-readme
=> feat: add IAM AuthN to Cloud SQL Sources

internal/server/mcp.go
Fixes that in SSL deployments, e.g. on k8s or cloud run the SSE endpoint was statically returning `http:` 
not a scheme based on request TLS attribute.
Fixes https://github.com/googleapis/genai-toolbox/issues/419
=> fix: #419 TLS https URL for SSE endpoint

.github/workflows/docs_deploy.yaml, .github/workflows/docs_preview_deploy.yaml, docs/en/getting-started/introduction/_index.md
Hugo's recent release seems to have broken docsy: https://github.com/gohugoio/hugo/issues/13599
There's a fix in progress: https://github.com/google/docsy/pull/2215
To unblock CI/CD, I've pinned hugo to 0.145.0 instead.
=> chore(ci/cd): pin version of hugo

.ci/integration.cloudbuild.yaml, .golangci.yaml, docs/en/resources/sources/bigtable.md, docs/en/resources/tools/bigtable-sql.md, go.mod, go.sum, internal/server/config.go, internal/sources/bigtable/bigtable.go, internal/sources/bigtable/bigtable_test.go, internal/tools/bigtable/bigtable.go, internal/tools/bigtable/bigtable_test.go, tests/bigtable_integration_test.go
A `bigtable` source can be added as the following example
```
sources:
test-bigtable-source:
kind: "bigtable"
project: "sample-project"
instance: "sample-instance"
```
A `bigtable` tool can be added as below
```
tools:
get-test-tool-data:
kind: bigtable-sql
source: test-bigtable-source
description: Some description
statement: SELECT * FROM `test-table` WHERE address['state'] = @state;
parameters:
- name: state
type: string
description: Filter by state
```
=> feat: Add Bigtable source and tool

.hugo/layouts/partials/page-meta-links.html
This PR fixes https://github.com/google/docsy/issues/2218.
This PR adds `layouts/partials/page-meta-links.html` to your repo which takes precedence over the original file from docsy theme (which is faulty). Don't forget to remove this file again once this issue is fixed in the docsy theme.
fixes #427
=> fix(docs): fix link 'Edit this page'

.hugo/hugo.toml
This PR changes the way the content dir is configured: it is now configured via a module mount.
As described in the [official docs](https://gohugo.io/configuration/all/#contentdir), this is a more flexible approach to configure this directory.
=> chore: Set content dir via mount

internal/server/api.go
Update http error code for invocation failure. Invocation may fail if user fail to provide required parameter etc.
Fixes #465
=> fix: update http error code from invocation

.ci/integration.cloudbuild.yaml, .golangci.yaml, docs/en/resources/sources/bigquery.md, docs/en/resources/tools/bigquery-sql.md, go.mod, go.sum, internal/server/config.go, internal/sources/bigquery/bigquery.go, internal/sources/bigquery/bigquery_test.go, internal/tools/bigquery/bigquery.go, internal/tools/bigquery/bigquery_test.go, tests/bigquery_integration_test.go, tests/common_test.go, tests/tool_test.go
A `BigQuery` source can be added as the following example:
```yaml
sources:
my-bigquery-source:
kind: bigquery
project: bigframes-dev
location: us # This field is optional
```
A `BigQuery` tool can be added as below:
```yaml
tools:
search-hotels-by-name:
kind: bigquery-sql
source: my-bigquery-source
description: Search for hotels based on name.
parameters:
- name: name
type: string
description: The name of the hotel.
```
=> feat: Add BigQuery source and tool

.github/label-sync.yml
Remove label sync that don't apply for this repo.
=> chore: remove automated label sync

internal/tools/http/http.go, tests/http/http_integration_test.go
Update http tools `Invoke` method.
* use `json.Unmarshal` for response body that are either list or json map. This will allow us to return lists as is (e.g. `[{map}]` instead of having to nest it in an additional list (e.g. `[]any{ [{map}] }`)
* for response body that are strings or fail to unmarshal, return it as is.
=> chore(http): update invocation results formatting

tests/alloydbpg/alloydb_pg_integration_test.go, tests/bigquery/bigquery_integration_test.go, tests/bigtable/bigtable_integration_test.go, tests/cloudsqlmssql/cloud_sql_mssql_integration_test.go, tests/cloudsqlmysql/cloud_sql_mysql_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/common.go, tests/http/http_integration_test.go, tests/mssql/mssql_integration_test.go, tests/mysql/mysql_integration_test.go, tests/postgres/postgres_integration_test.go, tests/spanner/spanner_integration_test.go, tests/sqlite/sqlite_integration_test.go, tests/tool.go
Remove cleaning `\\` or `\` in `got` and `want` strings of test cases. This is to prevent future the need to manually clean strings before comparing. This also allows us to be aware of the amount of backspace to prevent accidental escaping in src code.
Update integration test that is affected. This includes moving the `want` of test cases for `my-param-tool` invocation to each sources since spanner have a different format (return id as strings instead of int).
=> test: cleanup integration test

docs/en/resources/tools/postgres-execute-sql.md, internal/server/config.go, internal/tools/postgresexecutesql/postgresexecutesql.go, internal/tools/postgresexecutesql/postgresexecutesql_test.go
This tool can be used across all postgres sources.
`postgres-execute-sql` config is as below:
```
tools:
postgres_execute_sql_tool:
kind: "postgres-execute-sql"
source: my-alloydb-source // or any other sources that is compatible with this tool
description: Use this tool to execute sql.
```
The `postgres-execute-sql` tool takes one parameter. Example request as follow:
```
curl -X POST -H "Content-Type: application/json" -d '{"sql": "SELECT 1"}' http://127.0.0.1:5000/api/tool/postgres_execute_sql_tool/invoke
```
=> feat: add postgres-execute-sql tool

docs/en/resources/tools/mysql-sql.md
Updating description of MySQL tool to properly mention MySQL as it
has a typo and currently says SQL Server.
=> docs: update typo in MySQL tool

README.md, docs/en/concepts/telemetry/index.md, docs/en/getting-started/colab_quickstart.ipynb, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/getting-started/mcp_quickstart/_index.md, docs/en/how-to/deploy_docker.md, docs/en/how-to/deploy_toolbox.md, docs/en/samples/bigquery/colab_quickstart_bigquery.ipynb, docs/en/samples/bigquery/local_quickstart.md, docs/en/samples/bigquery/mcp_quickstart/_index.md
Updating docs to use the `--tools-file` flag over the now deprecated `--tools_file`.
The new flag was added as of `v0.3.0` in #384 
This change reduces confusion as current usage in docs results in
following message on startup of Toolbox server:
```sh
Flag --tools_file has been deprecated, please use --tools-file instead
```
Fixes #514
=> docs: use `--tools-file` over deprecated `--tools_file`

docs/en/resources/authServices/_index.md, docs/en/resources/tools/_index.md
The wording for `Authorized Invocations` reads a bit funny and has a typo.
Updating it to make a bit more sense and fixing a couple other typos around auth.
=> docs: update wording and typos for AuthServices

docs/en/getting-started/local_quickstart.md
Fix for #517 
This PR improves the Local Quickstart guide by adding troubleshooting advice for common PostgreSQL connection issues in [step 1](https://googleapis.github.io/genai-toolbox/getting-started/local_quickstart/#step-1-set-up-your-database).
This reduces friction and improves the setup experience for users following the local quickstart by addressing feedback in #517 regarding difficulties in the initial database connection step.
Users faced issues like password prompts or "role 'postgres' does not exist" errors when trying to connect to PostgreSQL with `psql -h 127.0.0.1 -U postgres`.
This PR adds a notice that provides solutions for common connection errors, including guidance on using `sudo -i -u postgres` for peer authentication.
=> docs: Address connection issues in local quickstart with clearer guidance

docs/en/samples/bigquery/local_quickstart.md
The `GoogleGenAI` llm directly takes in the `Project ID` [set up](https://googleapis.github.io/genai-toolbox/samples/bigquery/local_quickstart/#before-you-begin) in the quickstart. 
Partially fixes https://github.com/googleapis/genai-toolbox/issues/518
=> docs: use env-based project in LlamaIndex Quickstart

internal/server/mcp.go, tests/tool.go
MCP does not support the `authRequired` feature. Disallow all MCP Tool call to Tools with `authRequired` set.
Fixes: https://github.com/googleapis/genai-toolbox/issues/543
=> fix: prevent tool calls through MCP when auth is required

docs/en/how-to/export_telemetry.md
[`Running the Connector`](https://googleapis.github.io/genai-toolbox/how-to/export_telemetry/#running-the-connector) header should be `Running the Collector`.
Changing "Connector" --> "Collector".
=> docs: update typo in export_telemetry.md

internal/tools/http/http.go
`slices.Concat` will return `nil` if arrays are all empty instead of an empty slice `[]`. Fix this by setting `[]` if it's `nil`.
Fixes #564
=> fix: reinitialize required slice if nil

cmd/root.go, cmd/root_test.go, internal/server/config.go
Toolbox sends `debug` and `info` logs to `stdout`. However, in order to stupport stdio, Toolbox **should not** log messages to `stdout` as this will interfere with protocol operations. `stderr` are fine.
If `--stdio`, Toolbox will not send any `debug` and `info` logs, `warn` and `error` logs will still work as usual.
=> feat: add a new flag to indicate if stdio is supported

.github/workflows/lint.yaml, .golangci.yaml, cmd/root.go, internal/auth/google/google.go, internal/server/api.go, internal/sources/neo4j/neo4j.go, internal/sources/postgres/postgres.go, internal/tools/parameters.go, tests/alloydbpg/alloydb_pg_integration_test.go, tests/bigquery/bigquery_integration_test.go, tests/bigtable/bigtable_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/couchbase/couchbase_integration_test.go, tests/postgres/postgres_integration_test.go, tests/spanner/spanner_integration_test.go, tests/sqlite/sqlite_integration_test.go
gosimple had been deprecated in favor of staticcheck: https://github.com/golangci/golangci-lint/issues/357
Other requirements are all migrated.
`std-error-handling` exclusions is included because without that, it will ask to check all error returns from (`Close()`, or `os.Setenv`s, or `fmt.Fprint`s...
=> chore: migrate golangci-lint to v2

internal/server/mcp.go
Currently the `stdio` transport protocol will throw a `ZodError` during initialization. This is due to Toolbox writing `null` to stdout when it received a notification. This is not expected hence the `ZodError` occurs. Per the MCP protocol, notifications do not expect any response.
This fix added a condition to check if the responses is `nil` before writing to stdout.
=> fix(server/stdio): notifications should not return a response

internal/tools/mysqlsql/mysqlsql.go
@Yuan325  please review and merge this if all looks ok.
In existing code, for the character field with null values it will panic with error:
"panic: interface conversion: interface {} is nil, not []uint8"
=> fix(tools/mysqlsql): handled the null value for string case in mysqlsql tools

docs/en/resources/authServices/_index.md, docs/en/samples/bigquery/local_quickstart.md
This PR enhances our documentation by integrating `toolbox-core` code snippets into the quickstart examples on the docsite.
Previously, our client-facing documentation primarily showcased agent implementations using third-party frameworks like LangChain, LlamaIndex, and ADK. This created a documentation gap, as there were no baseline examples demonstrating how to use our foundational `toolbox-core` SDK directly. Users who wanted to build a custom integration without a specific framework had no direct reference in the guides.
This PR introduces a new "Core" tab to all relevant code examples within the auth services and local quickstart (with BigQuery) documentations.
=> docs: Add toolbox-core examples to quickstart guide

internal/server/server.go
Move config initialization (sources, authServices, tools, and toolsets) from within NewServer to a separate function, to allow reuse within dynamic reloading.
=> refactor: move config initialization out of NewServer

internal/tools/couchbase/couchbase.go, internal/tools/couchbase/couchbase_test.go, tests/alloydbpg/alloydb_pg_integration_test.go, tests/bigquery/bigquery_integration_test.go, tests/cloudsqlmssql/cloud_sql_mssql_integration_test.go, tests/cloudsqlmysql/cloud_sql_mysql_integration_test.go, tests/cloudsqlpg/cloud_sql_pg_integration_test.go, tests/common.go, tests/couchbase/couchbase_integration_test.go, tests/mssql/mssql_integration_test.go, tests/mysql/mysql_integration_test.go, tests/postgres/postgres_integration_test.go, tests/sqlite/sqlite_integration_test.go, tests/tool.go
Add templateParameters to support non-filter parameters and DDL statements.
Part of https://github.com/googleapis/genai-toolbox/issues/535
=> feat(tools/couchbase): add templateParameters field for couchbase

internal/server/mcp.go, internal/server/mcp/mcp.go, internal/server/mcp/v20250326/method.go, internal/server/mcp/v20250326/types.go, internal/server/mcp_test.go
Add v2025-03-26 version protocol [schema](https://github.com/modelcontextprotocol/modelcontextprotocol/blob/main/schema/2025-03-26/schema.ts) to Toolbox.
This PR also added: 
* tests for the v2025-03-26 protocol version
* update `internal/server/mcp/mcp.go` to include v20250326
* initialization response has to include "Mcp-Session-Id"
=> feat: add v20250326 schema

README.md, cmd/root.go, cmd/root_test.go, docs/en/getting-started/introduction/_index.md, docs/en/getting-started/local_quickstart.md, docs/en/how-to/connect_via_mcp.md, docs/en/samples/bigquery/local_quickstart.md, internal/server/config.go
Add flag `--disable-reload` to allow user to disable dynamic reloading for tools configuration file. 
If the flag is not included, dynamic reloading is enabled by default.
=> feat: add disable-reload flag and update docs

.github/workflows/docs_preview_deploy.yaml
The code for the preview build is now sourced from the target branch, whereas it was previously sourced from the main branch.
=> fix: fix docs preview deployment pipeline

docs/en/getting-started/introduction/_index.md
Using nested tabs in hugo is hard and flaky. So, we're using different heading for the multiple languages here.
=> docs: add introduction snippets for JS SDK

cmd/root.go, cmd/root_test.go, internal/server/mcp.go
Updates dynamic reloading to work for multiple forms of YAML config files.
This adjusts file-watching logic to account for the newly introduced changes in https://github.com/googleapis/genai-toolbox/pull/760.
=> feat: support multiple files for dynamic reloading

cmd/root.go, cmd/root_test.go
Update fsnotify comparison to check for WRITE events using the built-in `Event.Has()` method instead of `==` comparison (used in older versions). 
This is because fsnotify's `Op` type is a bit mask, and some systems may send multiple operations at once, which could be rejected by a standard `==` check. Previously this was causing the `TestSingleEdit` unit test to be flaky on Mac os.
=> fix: update fsnotify comparison

cmd/root.go
As long as the detected event's `e.Op` contains a write operation, only `WRITE` will be logged instead of the entire `e.Op` value. 
This ensures consistency for test cases across different operating systems. (Previously caused flaky `TestSingleEdit` as Mac os would occasionally count file-write events as `WRITE|CHMOD`
=> fix: update log to ensure consistent debug messages

README.md
This PR adds the Go SDK code snippets to the README, following the same pattern as Python and JS.
The code snippets are for:
- Core usage
- LangChain Go
- Genkit Go
- Go GenAI
- OpenAI Go
=> docs: Add Go SDK samples to the README

cmd/root.go, cmd/root_test.go
Allow fsnotify `CREATE` and `RENAME` events to trigger dynamic reload, instead of requiring `WRITE`.
This is due to some cases with specific editors/OS, (ex: vim on Mac), where file writes can potentially occur without ever triggering a `WRITE` operation on the watched tools file, but solely through creation and renaming of .swp files.
=> fix: trigger reload on additional fsnotify operations

README.md
Adding badge that links to docs to make them more easily discoverable from README.
Updating discord badge to match other two with "flat" style.
=> chore: add docs readme badge and update discord to match style

docs/en/getting-started/mcp_quickstart/_index.md
This pr updates the docs, specifically the quickstart working with MCP Inspector. The tool recently included a Session Token for Authorization that can easily be missed, this updates the guide to make it easy to find and use this Session Token
=> docs: update MCP inspector instructions

internal/tools/parameters.go, internal/tools/parameters_test.go
Added an option for user to indicate if the parameter is required. 
Example:
```
parameters:
- name: foo
type: string
description: foo
required: false
```
If the `required` field is not provided, it will be defaulted to `true`. 
If a `default` value is provided, `required = false` regardless if the field is indicated.
```
parameters:
- name: foo
type: string
description: foo
default: hello world
```
Fixes #736
=> feat: add support for null optional parameter

README.md
Link to [Medium Publication for Toolbox](https://medium.com/@mcp_toolbox) from badge.
=> chore: add medium badge to README that links to Toolbox Publication

internal/server/mcp.go, internal/server/mcp/mcp.go, internal/server/mcp_test.go
When the server receives a request with an invalid or unsupported `MCP-Protocol-Version`, it MUST respond with `400 Bad Request`.
=> chore: response with 400 Bad Request when receive invalid request

docs/en/how-to/connect_via_mcp.md
Add `2025-06-18` to list of supported MCP versions. Sort list to latest version first.
=> docs: add mcp v2025-06-18 to supported mcp version

internal/tools/http/http.go
Replace `nil` values with empty string for query parameter.
=> chore(tools/http): replace nil query parameter with empty string

docs/en/resources/sources/valkey.md
In [genai-toolbox](https://googleapis.github.io/genai-toolbox/resources/sources/valkey/) Official Documentation of valkey URL is broken.
=> docs: fix valkey doc broken link

internal/prebuiltconfigs/tools/cloud-sql-mysql.yaml
This PR consist of two fixes: 
1. Added `default` to table_names parameter since the default value is an empty string.
2. Update the sql statement for reusing parameter within the statement.
Fixes partial #877
=> fix(prebuilt/cloud-sql-mysql): update list_table tool

internal/sources/bigquery/bigquery.go, internal/tools/bigquery/bigqueryexecutesql/bigqueryexecutesql.go, tests/bigquery/bigquery_integration_test.go
- Added a dry run step to identify the query type (e.g., SELECT, DML), which allows the tool to correctly handle the query's output.
- The recommended high-level client, cloud.google.com/go/bigquery, does not expose the statement type from a dry run. To circumvent this limitation, the low-level BigQuery REST API client (google.golang.org/api/bigquery/v2) was added to gain access to these necessary details.
fixes: #915
=> fix(tools/bigquery-execute-sql): ensure invoke always returns a non-null value

internal/server/web_test.go
Update `web_test` to verify linked resources such as the `style.css` file and `.js` components are accessible. 
Also added test cases to check URLs with and without a trailing slash (ex: `/ui` and `/ui/`).
=> test(internal/server): update web tests to verify resource paths

docs/en/getting-started/local_quickstart_js.md
Enhance the [JavaScript Quickstart](https://googleapis.github.io/genai-toolbox/getting-started/local_quickstart_js/) by adding a new tab dedicated to integrating the MCP Toolbox with LlamaIndex. This provides users with a direct, runnable example of how to utilize Toolbox's capabilities within a LlamaIndex-powered LLM agent for hotel search and booking operations.
The changes include:
- Addition of a new `LlamaIndex` tab in `docs/quickstarts/js-local.md`.
- Corresponding `hotelAgent.js` code snippet for LlamaIndex integration.
This PR addresses and resolves #930.
=> docs: add llamaindex integration to js quickstart

.github/workflows/docs_preview_deploy.yaml
The checkout actions uses ref as `github.sha` by default. For forked repos, this refers to the last commit on the main branch ([ref](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#fork)).
This means that the docs preview pipeline when run on forked PRs does not allow us to preview changes made in the PR.
`github.event.pull_request.head.sha` allows to to checkout the latest commit on the forked PR.
=> fix: fix document preview pipeline for forked PRs

.github/labels.yaml
The `sync label` job failed during PR merge due to fail parsing.
=> chore: fix labels description

internal/tools/mysql/mysqlsql/mysqlsql.go
mysql driver return []uint8 types for "JSON", hence we will need to cast it.
Toolbox will unmarshal JSON data retrieved from database during invocation. If directly convert results into string, it will be marshaled again when returning results to the user (causing double marshaling). 
Fixes #840
=> fix(tools/mysqlsql): unmarshal json data from database during invoke

internal/server/static/css/style.css, internal/server/static/js/toolDisplay.js, internal/server/static/tools.html
Add instructions for obtaining a valid id_token to include in the request header for auth params.
Uses a drop-down menu with two separate tabs to distinguish between users with a standard account and service account, defaulting to standard account.
=> feat: add token instructions to header modal

internal/server/static/css/style.css, internal/server/static/js/auth.js, internal/server/static/js/loadTools.js, internal/server/static/js/toolDisplay.js, internal/server/static/tools.html, internal/server/static/toolsets.html
Add `Sign in with Google` button within Toolbox UI's `Edit Header` modal that automatically retrieves a valid ID token for users based on an input clientID.
This should make it significantly easier/faster for users to format request headers properly and test tools that use auth.
=> feat: add login with google button for automatic id token retrieval

internal/tools/mssql/mssqlexecutesql/mssqlexecutesql.go, internal/tools/mysql/mysqlexecutesql/mysqlexecutesql.go, internal/tools/neo4j/neo4jexecutecypher/neo4jexecutecypher.go, internal/tools/postgres/postgresexecutesql/postgresexecutesql.go, internal/tools/spanner/spannerexecutesql/spannerexecutesql.go, internal/tools/tidb/tidbexecutesql/tidbexecutesql.go
It's safer and also more readable to access params by map.
=> chore: Access params by maps for execute-sql tools

.ci/integration.cloudbuild.yaml
---
Disabling Dataplex integration tests due to test failure. This is blocking PRs from merging.
🛠️ Ref #1250
=> ci: disabling dataplex integration tests due to failure

internal/tools/bigquery/bigquerysql/bigquerysql.go
---
The `useClientOAuth` config was moved from the tool into `bigquery` source in #1279, however the config was not removed from the source. The value is now retrieved from the source instead of setting it directly.
=> fix(tools/bigquerysql)!: remove `useClientOAuth` from tools config

.github/PULL_REQUEST_TEMPLATE.md
Should link to the Toolbox repo
=> docs: Fix PR template link

CONTRIBUTING.md, DEVELOPER.md
Add guidelines for MCP Toolbox tools naming properties: **tool name** and **tool kind**.
=> docs: add tools naming convention

cmd/root.go, docs/en/resources/sources/cloud-sql-admin.md, internal/sources/cloudsqladmin/cloud_sql_admin.go, internal/sources/cloudsqladmin/cloud_sql_admin_test.go
---
This PR introduces the `cloud-sql-admin` source, which provides a client for the Google Cloud SQL Admin API.
```
sources:
my-cloud-sql-admin:
kind: cloud-sql-admin
```
---
=> feat(source/cloudsqladmin): Add cloud sql admin source

docs/en/resources/tools/alloydb/alloydb-list-instances.md, docs/en/resources/tools/alloydb/alloydb-list-users.md, internal/sources/alloydbadmin/alloydbadmin.go, internal/tools/alloydb/alloydbgetcluster/alloydbgetcluster.go, internal/tools/alloydb/alloydblistclusters/alloydblistclusters.go, internal/tools/alloydb/alloydblistinstances/alloydblistinstances.go, internal/tools/alloydb/alloydblistusers/alloydblistusers.go
---
- This PR introduces a userAgentRoundTripper that prepends our custom user agent to the existing User-Agent header
- Moves alloydb api client to `alloydb-admin` source
- Updates alloydb control plane tools (`alloydb-get-cluster`, `alloydb-list-clusters`, `alloydb-list-instances`, `alloydb-list-users`)  accordingly.
---
=> feat(source/alloydb-admin): Add user agent and attach alloydb api in alloydb-admin source
